const ACTION_EVENTS = {
  GET_ITEMS: "GET_ITEMS",
  ADD_ITEMS: "ADD_ITEMS",
  DELETE_ITEMS: "DELETE_ITEMS",
  ITEMS_LOADING: "ITEMS_LOADING",
  USER_LOADING: "USER_LOADING",
  USER_LOADED: "USER_LOADED",
  AUTH_ERROR: "AUTH_ERROR",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  GET_ERRORS: "GET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
};

export default ACTION_EVENTS;
